name: 🪲 Bug Report
description: Something doesn’t work as expected with the Events Server
title: "[Bug] "
labels: ["Bug"]
assignees:
  - ShookEagle
type: bug
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen.
      placeholder: When I click X, Y happens instead of Z…
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: Numbered steps, please.
      placeholder: |
        1. …
        2. …
        3. …
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: [ "P0 - Critical", "P1 - High", "P2 - Medium", "P3 - Low" ]
      default: 2
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      render: shell