name: 🪲 Bug Report
description: Something doesn’t work as expected with the Events Server.
title: "[Bug] "
labels:
  - "type::1 Bug"
  - "status::1 Triage"
assignees:
  - ShookEagle
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen.
      placeholder: When I do X, Y happens instead of Z…
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: Numbered steps, please.
      placeholder: |
        1. …
        2. …
        3. …
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      render: shell